#!/usr/bin/env bash
# A script to transfer a file to the server
#
# Declaration of variables
localFile=$1 # Path to local file
ipAddress=$2 # IP address
userName=$3 # Username on server
pathToSSHPrivateKey=$4 # Path to private SSH key
#
# Check if command line arguments are less than 3
# $# is the length of command line arguments
if [ $# -lt 3 ];
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o StrictHostKeyChecking=no -i "$pathToSSHPrivateKey" "$localFile" "$userName"@"$ipAddress":~/
fi