#!/usr/bin/env bash
# configure a nginx server on ubuntu so /redirect_me moves to a new page
# It is a permanent redirect

apt-get update -y
apt-get install nginx -y

rm /etc/nginx/nginx.conf

printf %s "
http
{
	server {
    	listen 80;
    	root   /;

    	location /redirect_me {
        return 301 https://www.youtube.com/watch?v=3oPEKw-qS1A&list=RD3oPEKw-qS1A&start_radio=1&ab_channel=Rayvanny;
    	}
    	}
}" > /etc/nginx/nginx.conf
