#!/usr/bin/env bash
# Configures an Nginx server so that /redirect_me redirects to another page.


# exit on error and return 1
set -e


# Upadating Packages before Installations
sudo apt-get update -y
sudo apt-get install -y nginx
sudo apt-get upgrade -y

# Creating an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Performing a 301 Redirection
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/youtube.com\/ permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Creating a 404 Custom error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
new_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default

# Reloading Nginx service
sudo nginx -s reload
sudo nginx -t

sudo service nginx restart
