#!/usr/bin/env bash
# A script to read contents of the etc/passwd file
# Then it delimits them giving username =, id and home dir

while IFS= read -r line
do
	cut -d ':' -f1,3,6<<<"$line"
done<'/etc/passwd'
