#!/usr/bin/env bash
# A script to read contents of the etc/passwd file
# Then it delimits them giving username =, id and home dir

for line in $(cat '/etc/passwd')
do
	IFS=':'
	read -r name password id group useridinf home shell <<<"$line"
	echo -n "$name"
	echo -n ":"
	echo -n "$id"
	echo -n ":"
	echo "$home"
done
