#!/usr/bin/env bash
# A script to read contents of the etc/passwd file
# Then it delimits them giving username =, id and home dir

while IFS=: read -r user pass id gid uidinf home shel
do
	echo "The user $user is part of the $gid gang, lives in $home and rides $shel. $id's place is protected by the passcode $pass more info about the user here: $uidinf"
done<'/etc/passwd'
