#!/usr/bin/env bash
# This script print Best School 10 times using the while loop

i=1
while [ $i -lt 11 ]
do
    if [ $i = 9 ]
    then
	echo "Best School"
	echo "Hi"
	i=$(( i + 1 ))
	continue
    fi
echo "Best School"
	i=$(( i + 1 ))
done
