#!/usr/bin/env bash
# This file changes the ip addresses in the local dns

cp /etc/hosts changes
sed -i 's/127.0.0.1	localhost/127.0.0.2	localhost/g'	changes
sed -i -e '/^* facebook.com$/{
    s/* facebook.com/8.8.8.8	facebook.com/
    t next
    a\
8.8.8.8  facebook.com
}:q' changes
cp -f changes /etc/hosts
